name: Clone from Dev to Dev site with Docker and Python

on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [ dev, testing-actions ]
  pull_request:
    branches: [ dev ]
    types: [closed]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      - name: Pushes to another repository
        uses: LACMTA/github-action-push-to-another-repo@testing
        # env:
          # METRO_GITHUB_TOKEN: ${{ secrets.METRO_GITHUB_TOKEN }}
        with:
          github-token: ${{ secrets.METRO_GITHUB_TOKEN }}
